version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    pre_build:
      - python -m pip install -U pip
      - python -m pip install -r docs/requirements.txt
      - python -m pip install -e . --no-deps
      
sphinx:
  configuration: docs/source/conf.py

python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
